### ISSUE TITLE
Expo integration - TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by timothymiller** [nderscore/tamagui-typescript-plugin#3]
## Background

Experiencing this issue when following [the Expo setup](https://github.com/nderscore/tamagui-typescript-plugin#usage-in-expo-only-no-nextjs-tamagui-projects) with the [T4 app repo](https://github.com/timothymiller/t4-app).

## Stack trace

```bash
apps/expo postinstall$ cross-env TAMAGUI_TARGET=native node generate-tamagui-json.js
│ 
│     ➡ [tamagui] (197ms):
│ 
│         Config     ./.tamagui/tamagui.config.cjs
│         Components ./.tamagui/tamagui-components.config.cjs
│         
│ The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is link…
│ No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
│ ⚠️ Tamagui Warning [001]: Skipping loading /Users/timothymiller/workspace/t4-app/apps/expo/.tamagui/tamagui.config.cjs due to error…
│    - message: (0 , _codegenNativeComponent.default) is not a function
│    - for more info see: https://tamagui.dev/docs/intro/errors#warning-001
│    - set TAMAGUI_SHOW_FULL_BUNDLE_ERRORS=1 to see stack trace
│ /Users/timothymiller/workspace/t4-app/node_modules/@tamagui/core-node/dist/index.js:40901
│       const defaultFont = `$${defaultFontName}`;
│                               ^
│ TypeError: Cannot convert object to primitive value
│     at createTamagui (/Users/timothymiller/workspace/t4-app/node_modules/@tamagui/core-node/dist/index.js:40901:31)
│     at loadTamagui (/Users/timothymiller/workspace/t4-app/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:71:55)
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│ Node.js v18.17.0
```

**Comment by nderscore** [comment]
Pretty weird error! When `TAMAGUI_TARGET=native` is set, the `defaultFontName` in that part of `@tamagui/core-node` is undefined. This might be a Tamagui bug (or just an error with my naive workaround script :sweat_smile:)

If you set `TAMAGUI_TARGET=web` instead, it works fine though :shrug: 

The theme keys shouldn't change between apps, so the value of the `TAMAGUI_TARGET` environment variable doesn't matter for generating the JSON cache.

---

That said, since the T4 App template is a monorepo with a Next.js app, so you really don't need to use this workaround at all.

You should be able to use the Next.js app's path for the `pathToApp` setting.

The `generate-tamagui-json` workaround is meant for Expo-only apps (no Next.js)

**Comment by timothymiller** [comment]
Yep, changing `TAMAGUI_TARGET` to web fixed the issue.
